from PyQt5.Qt import *
import time

class processbar_UI(QDialog):
    def __init__(self,thread_class):
        super().__init__()
        self.dialog_init()
        self.sta(thread_class)
        #self.finish()
    def dialog_init(self):
        font=QFont()
        font.setFamily('宋体')
        font.setPointSize(20)
        self.setWindowTitle('Guide progressbar')
        self.setFont(font)
        self.setFixedHeight(50)
        self.setFixedWidth(400)
        vbox=QVBoxLayout()
        self.prgs = QProgressBar(self)
        self.prgs.setMinimum(0)
        self.prgs.setMaximum(0)
        self.prgs.setGeometry(300,400,200,250)
        deskrect = QApplication.desktop()
        self.move(deskrect.width() - self.width(), 0)
        self.prgs.setStyleSheet("QProgressBar{background-color:#E0E0E0;border:2px solid #5B677A;border-radius:5px;text-align:center}"
                "QProgressBar::chunk{background-color:#5B677A;width:10px;margin:0.5px;border-radius:5px;}")
        vbox.addWidget(self.prgs)
        self.setLayout(vbox)
    def finish(self):
        self.prgs.setMaximum(100)
        self.prgs.setValue(100)
        time.sleep(1)
        self.close()
    def sta(self,thread_class):
        self.cal = thread_class
        self.cal.finished.connect(self.finish)
        self.cal.start()

# class drill_compensation_UI(QDialog):
#     statue = True
#     def __init__(self):
#         super().__init__()
#         self.init_UI()
#         self.connect_init()   
#     def init_UI(self):
#         self.setObjectName("Form")
#         self.resize(1125, 742)
#         self.hole_compensation_gb = QGroupBox(self)
#         self.hole_compensation_gb.setGeometry(QRect(120, 120, 761, 361))
#         self.hole_compensation_gb.setObjectName("hole_compensation_gb")
#         self.round_hole_gb = QGroupBox(self.hole_compensation_gb)
#         self.round_hole_gb.setGeometry(QRect(10, 30, 711, 111))
#         self.round_hole_gb.setObjectName("round_hole_gb")
#         self.horizontalLayoutWidget = QWidget(self.round_hole_gb)
#         self.horizontalLayoutWidget.setGeometry(QRect(10, 20, 651, 80))
#         self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
#         self.horizontal_ly = QHBoxLayout(self.horizontalLayoutWidget)
#         self.horizontal_ly.setContentsMargins(0, 0, 0, 0)
#         self.horizontal_ly.setObjectName("horizontal_ly")
#         self.npth_lbl = QLabel(self.horizontalLayoutWidget)
#         self.npth_lbl.setObjectName("npth_lbl")
#         self.horizontal_ly.addWidget(self.npth_lbl)
#         self.npth_spx = QDoubleSpinBox(self.horizontalLayoutWidget)
#         self.npth_spx.setDecimals(4)
#         self.npth_spx.setObjectName("npth_spx")
#         self.horizontal_ly.addWidget(self.npth_spx)
#         self.pth_lbl = QLabel(self.horizontalLayoutWidget)
#         self.pth_lbl.setObjectName("pth_lbl")
#         self.horizontal_ly.addWidget(self.pth_lbl)
#         self.pth_spx = QDoubleSpinBox(self.horizontalLayoutWidget)
#         self.pth_spx.setDecimals(4)
#         self.pth_spx.setObjectName("pth_spx")
#         self.horizontal_ly.addWidget(self.pth_spx)
#         self.via_lbl = QLabel(self.horizontalLayoutWidget)
#         self.via_lbl.setObjectName("via_lbl")
#         self.horizontal_ly.addWidget(self.via_lbl)
#         self.via_spx = QDoubleSpinBox(self.horizontalLayoutWidget)
#         self.via_spx.setDecimals(4)
#         self.via_spx.setObjectName("via_spx")
#         self.horizontal_ly.addWidget(self.via_spx)
#         self.blind_lbl = QLabel(self.horizontalLayoutWidget)
#         self.blind_lbl.setObjectName("blind_lbl")
#         self.horizontal_ly.addWidget(self.blind_lbl)
#         self.blind_spx = QDoubleSpinBox(self.horizontalLayoutWidget)
#         self.blind_spx.setDecimals(4)
#         self.blind_spx.setObjectName("blind_spx")
#         self.horizontal_ly.addWidget(self.blind_spx)
#         self.bury_lbl = QLabel(self.horizontalLayoutWidget)
#         self.bury_lbl.setObjectName("bury_lbl")
#         self.horizontal_ly.addWidget(self.bury_lbl)
#         self.bury_spx = QDoubleSpinBox(self.horizontalLayoutWidget)
#         self.bury_spx.setDecimals(4)
#         self.bury_spx.setObjectName("bury_spx")
#         self.horizontal_ly.addWidget(self.bury_spx)
#         self.solt_hole_gb = QGroupBox(self.hole_compensation_gb)
#         self.solt_hole_gb.setGeometry(QRect(10, 160, 711, 121))
#         self.solt_hole_gb.setObjectName("solt_hole_gb")
#         self.horizontalLayoutWidget_2 = QWidget(self.solt_hole_gb)
#         self.horizontalLayoutWidget_2.setGeometry(QRect(10, 20, 651, 80))
#         self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
#         self.horizontal2_ly = QHBoxLayout(self.horizontalLayoutWidget_2)
#         self.horizontal2_ly.setContentsMargins(0, 0, 0, 0)
#         self.horizontal2_ly.setObjectName("horizontal2_ly")
#         self.npthlg_lbl = QLabel(self.horizontalLayoutWidget_2)
#         self.npthlg_lbl.setObjectName("npthlg_lbl")
#         self.horizontal2_ly.addWidget(self.npthlg_lbl)
#         self.npthlong_spx = QDoubleSpinBox(self.horizontalLayoutWidget_2)
#         self.npthlong_spx.setDecimals(4)
#         self.npthlong_spx.setObjectName("npthlong_spx")
#         self.horizontal2_ly.addWidget(self.npthlong_spx)
#         self.npthwe_lbl = QLabel(self.horizontalLayoutWidget_2)
#         self.npthwe_lbl.setObjectName("npthwe_lbl")
#         self.horizontal2_ly.addWidget(self.npthwe_lbl)
#         self.npthwide_spx = QDoubleSpinBox(self.horizontalLayoutWidget_2)
#         self.npthwide_spx.setDecimals(4)
#         self.npthwide_spx.setObjectName("npthwide_spx")
#         self.horizontal2_ly.addWidget(self.npthwide_spx)
#         self.pthlg_lbl = QLabel(self.horizontalLayoutWidget_2)
#         self.pthlg_lbl.setObjectName("pthlg_lbl")
#         self.horizontal2_ly.addWidget(self.pthlg_lbl)
#         self.pthlong_spx = QDoubleSpinBox(self.horizontalLayoutWidget_2)
#         self.pthlong_spx.setDecimals(4)
#         self.pthlong_spx.setObjectName("pthlong_spx")
#         self.horizontal2_ly.addWidget(self.pthlong_spx)
#         self.pthwe_lbl = QLabel(self.horizontalLayoutWidget_2)
#         self.pthwe_lbl.setObjectName("pthwe_lbl")
#         self.horizontal2_ly.addWidget(self.pthwe_lbl)
#         self.pthwide_spx = QDoubleSpinBox(self.horizontalLayoutWidget_2)
#         self.pthwide_spx.setDecimals(4)
#         self.pthwide_spx.setObjectName("pthwide_spx")
#         self.horizontal2_ly.addWidget(self.pthwide_spx)

#         self.Continue_ptn = QPushButton(self.hole_compensation_gb)
#         self.Continue_ptn.setGeometry(QRect(230, 320, 75, 23))
#         self.Continue_ptn.setObjectName("Continue_ptn")
#         self.stop_ptn = QPushButton(self.hole_compensation_gb)
#         self.stop_ptn.setGeometry(QRect(400, 320, 75, 23))
#         self.stop_ptn.setObjectName("stop_ptn")
        
#         self.retranslateUi()

#     def retranslateUi(self):
#         _translate = QCoreApplication.translate
#         self.setWindowTitle(_translate("Form", "Form"))
#         self.hole_compensation_gb.setTitle(_translate("Form", "孔补偿"))
#         self.round_hole_gb.setTitle(_translate("Form", "圆孔"))
#         self.npth_lbl.setText(_translate("Form", "NPTH ："))
#         self.pth_lbl.setText(_translate("Form", "PTH ："))
#         self.via_lbl.setText(_translate("Form", "VIA："))
#         self.blind_lbl.setText(_translate("Form", "盲孔："))
#         self.bury_lbl.setText(_translate("Form", "埋孔："))
#         self.solt_hole_gb.setTitle(_translate("Form", "槽孔"))
#         self.npthlg_lbl.setText(_translate("Form", "NPTH长："))
#         self.npthwe_lbl.setText(_translate("Form", "NPTH宽："))
#         self.pthlg_lbl.setText(_translate("Form", "PTH长："))
#         self.pthwe_lbl.setText(_translate("Form", "PTH宽："))
#         self.Continue_ptn.setText(_translate("Form", "Continue"))
#         self.stop_ptn.setText(_translate("Form", "stop"))

#     def connect_init(self):
#         self.Continue_ptn.clicked.connect(self.continue_clicked)
#         self.stop_ptn.clicked.connect(self.stop_clicked)

#     def continue_clicked(self):
#         self.statue = True
#         self.close()

#     def stop_clicked(self):
#         self.statue = False
#         self.close()


