# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PythonProject\demo\login.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        login.setFont(font)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 70, 251, 401))
        self.frame.setStyleSheet("#frame{border-radius:20px;background-image: url(:/新前缀/img/th.jpg);}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 181, 91))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 807 12pt \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 270, 131, 81))
        self.label.setStyleSheet("font: 8pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(410, 80, 281, 391))
        self.frame_2.setStyleSheet("#frame_2{background-color:rgba(255, 255, 255, 100);\n"
"\n"
"border-radius:20px;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 70, 251, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_2 = QtWidgets.QWidget()
        self.login_2.setObjectName("login_2")
        self.lineEdit = QtWidgets.QLineEdit(self.login_2)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 113, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setStyleSheet("border-style:outset;\n"
"background-image: url(:/新前缀/img/th (1).jpg);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.login_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 72, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.login_2)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 72, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.login_2)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 110, 113, 21))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-style:outset;\n"
"background-image: url(:/新前缀/img/th.jpg);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.login_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 191, 28))
        self.pushButton.setStyleSheet("background-image: url(:/新前缀/img/th.jpg);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.login_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 240, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.login_2)
        self.res = QtWidgets.QWidget()
        self.res.setObjectName("res")
        self.pushButton_2 = QtWidgets.QPushButton(self.res)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 200, 191, 28))
        self.pushButton_2.setStyleSheet("background-image: url(:/新前缀/img/th.jpg);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.res)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 20, 113, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_4.setStyleSheet("border-style:outset;\n"
"background-image: url(:/新前缀/img/th (1).jpg);")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.res)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 72, 21))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.res)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 72, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.res)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 140, 113, 21))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-style:outset;\n"
"background-image: url(:/新前缀/img/th.jpg);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_11 = QtWidgets.QLabel(self.res)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 72, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.res)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 80, 113, 21))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("border-style:outset;\n"
"background-image: url(:/新前缀/img/th.jpg);")
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.res)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 240, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.res)
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.label_3.setText(_translate("login", "欢迎来到小孟\n"
"的乐园"))
        self.label.setText(_translate("login", "加油，你也是最棒的"))
        self.label_2.setText(_translate("login", "账号："))
        self.label_4.setText(_translate("login", "密码："))
        self.pushButton.setText(_translate("login", "登录"))
        self.pushButton_5.setText(_translate("login", "注册"))
        self.pushButton_2.setText(_translate("login", "注册"))
        self.label_6.setText(_translate("login", "确认密码："))
        self.label_5.setText(_translate("login", "账号："))
        self.label_11.setText(_translate("login", "密码："))
        self.pushButton_6.setText(_translate("login", "返回登录"))

import res_rc
