from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
import time

class processbar_UI(QDialog):
    def __init__(self,thread_class):
        super().__init__()
        self.dialog_init()
        self.sta(thread_class)
        #self.finish()
    def dialog_init(self):
        font=QFont()
        font.setFamily('宋体')
        font.setPointSize(20)
        self.setWindowTitle('Guide progressbar')
        self.setFont(font)
        self.setFixedHeight(50)
        self.setFixedWidth(400)
        vbox=QVBoxLayout()
        self.prgs = QProgressBar(self)
        self.prgs.setMinimum(0)
        self.prgs.setMaximum(0)
        self.prgs.setGeometry(300,400,200,250)
        deskrect = QApplication.desktop()
        self.move(deskrect.width() - self.width(), 0)
        self.prgs.setStyleSheet("QProgressBar{background-color:#E0E0E0;border:2px solid #5B677A;border-radius:5px;text-align:center}"
                "QProgressBar::chunk{background-color:#5B677A;width:10px;margin:0.5px;border-radius:5px;}")
        vbox.addWidget(self.prgs)
        self.setLayout(vbox)
    def finish(self):
        self.prgs.setMaximum(100)
        self.prgs.setValue(100)
        time.sleep(1)
        self.close()
    def sta(self,thread_class):
        self.cal = thread_class
        self.cal.finished.connect(self.finish)
        self.cal.start()

class outter_compensation_UI(QDialog):
    statue = True
    def __init__(self):
        super().__init__()
        self.init_UI()
        self.connect_init()  
    def init_UI(self):    
        self.setObjectName("Form")
        self.resize(662, 260)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 601, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.trace_ly = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.trace_ly.setContentsMargins(0, 0, 0, 0)
        self.trace_ly.setObjectName("trace_ly")
        self.trace_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.trace_lbl.setObjectName("trace_lbl")
        self.trace_ly.addWidget(self.trace_lbl)
        self.trace_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.trace_dsb.setDecimals(3)
        self.trace_dsb.setValue(0.500)
        self.trace_dsb.setObjectName("trace_dsb")
        self.trace_ly.addWidget(self.trace_dsb)
        self.surface_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.surface_lbl.setObjectName("surface_lbl")
        self.trace_ly.addWidget(self.surface_lbl)
        self.surface_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.surface_dsb.setDecimals(3)
        self.surface_dsb.setObjectName("surface_dsb")
        self.trace_ly.addWidget(self.surface_dsb)
        self.mark_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mark_lbl.setObjectName("mark_lbl")
        self.trace_ly.addWidget(self.mark_lbl)
        self.mark_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.mark_dsb.setDecimals(3)
        self.mark_dsb.setValue(2.000)
        self.mark_dsb.setObjectName("mark_dsb")
        self.trace_ly.addWidget(self.mark_dsb)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 601, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.pth_ly = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.pth_ly.setContentsMargins(0, 0, 0, 0)
        self.pth_ly.setObjectName("pth_ly")
        self.pth_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.pth_lbl.setObjectName("pth_lbl")
        self.pth_ly.addWidget(self.pth_lbl)
        self.pth_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.pth_dsb.setDecimals(3)
        self.pth_dsb.setObjectName("pth_dsb")
        self.pth_ly.addWidget(self.pth_dsb)
        self.via_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.via_lbl.setObjectName("via_lbl")
        self.pth_ly.addWidget(self.via_lbl)
        self.via_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.via_dsb.setDecimals(3)
        self.via_dsb.setObjectName("via_dsb")
        self.pth_ly.addWidget(self.via_dsb)
        self.tear_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.tear_lbl.setObjectName("tear_lbl")
        self.pth_ly.addWidget(self.tear_lbl)
        self.tear_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.tear_dsb.setDecimals(3)
        self.tear_dsb.setObjectName("tear_dsb")
        self.pth_ly.addWidget(self.tear_dsb)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 150, 601, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.smd_ly = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.smd_ly.setContentsMargins(0, 0, 0, 0)
        self.smd_ly.setObjectName("smd_ly")
        self.smd_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.smd_lbl.setObjectName("smd_lbl")
        self.smd_ly.addWidget(self.smd_lbl)
        self.smd_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.smd_dsb.setDecimals(3)
        self.smd_dsb.setValue(2.000)
        self.smd_dsb.setObjectName("smd_dsb")
        self.smd_ly.addWidget(self.smd_dsb)
        self.bga_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.bga_lbl.setObjectName("bga_lbl")
        self.smd_ly.addWidget(self.bga_lbl)
        self.bga_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.bga_dsb.setDecimals(3)
        self.bga_dsb.setValue(2.000)
        self.bga_dsb.setObjectName("bga_dsb")
        self.smd_ly.addWidget(self.bga_dsb)
        self.small_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.small_lbl.setObjectName("small_lbl")
        self.smd_ly.addWidget(self.small_lbl)
        self.samll_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.samll_dsb.setDecimals(3)
        self.samll_dsb.setObjectName("samll_dsb")
        self.smd_ly.addWidget(self.samll_dsb)
        self.compensate_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.compensate_lbl.setObjectName("compensate_lbl")
        self.smd_ly.addWidget(self.compensate_lbl)
        self.compensate_dsb = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.compensate_dsb.setDecimals(3)
        self.compensate_dsb.setObjectName("compensate_dsb")
        self.smd_ly.addWidget(self.compensate_dsb)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 190, 601, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.continue_ly = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.continue_ly.setContentsMargins(0, 0, 0, 0)
        self.continue_ly.setObjectName("continue_ly")
        self.continue_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.continue_btn.setObjectName("continue_btn")
        self.continue_ly.addWidget(self.continue_btn)
        self.stop_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.stop_btn.setObjectName("stop_btn")
        self.continue_ly.addWidget(self.stop_btn)
        self.unit_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.unit_lbl.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.unit_lbl.setObjectName("unit_lbl")
        self.unit_cmb = QtWidgets.QComboBox(self.groupBox_2)
        self.unit_cmb.setGeometry(QtCore.QRect(80, 30, 69, 22))
        self.unit_cmb.setObjectName("unit_cmb")
        self.unit_cmb.addItem("")
        self.unit_cmb.addItem("")
        self.horizontalLayout_4.addWidget(self.groupBox_2)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "外层补偿(整体)"))
        self.trace_lbl.setText(_translate("Form", "线(Trace)："))
        self.surface_lbl.setText(_translate("Form", "大铜面(Surface):"))
        self.mark_lbl.setText(_translate("Form", "光学点(Mark):"))
        self.pth_lbl.setText(_translate("Form", "PTH Pad:"))
        self.via_lbl.setText(_translate("Form", "VIA Pad:"))
        self.tear_lbl.setText(_translate("Form", "泪滴属性(Tear_Drop):"))
        self.smd_lbl.setText(_translate("Form", "贴件(SMD):"))
        self.bga_lbl.setText(_translate("Form", "球状贴件(BGA):"))
        self.small_lbl.setText(_translate("Form", "小于："))
        self.compensate_lbl.setText(_translate("Form", "补偿："))
        self.continue_btn.setText(_translate("Form", "continue"))
        self.stop_btn.setText(_translate("Form", "stop"))
        self.unit_lbl.setText(_translate("Form", "单位："))
        self.unit_cmb.setItemText(0, _translate("Form", "mil"))
        self.unit_cmb.setItemText(1, _translate("Form", "mm"))

    def connect_init(self):
        self.continue_btn.clicked.connect(self.continue_clicked)
        self.stop_btn.clicked.connect(self.stop_clicked)

    def continue_clicked(self):
        self.statue = True
        self.close()

    def stop_clicked(self):
        self.statue = False
        self.close()

